### ISSUE TITLE
Sprint#2 tasks

### ISSUE THREAD

**Issue by mar-bi** [chingu-voyage6/grad.then#239]
The list of **Sprint#2** tasks:
 - [ ] User Story: Button in `Hero` #129
 - [ ] ~~Apollo setup for Gatsby #235~~ (blocked)
 - [ ] ~~Move app state to `apollo-link-state` #237~~ (blocked)
 - [x] Handle environment variables with `dotenv` #223 
 - [ ] setup UI testing #230 
 - [x] README update #233 
 - [ ] test backend with `graphcool` and `gatsby-source-graphcms`
